api/urls.py
from django.urls import path
from .views import api

urlpatterns = [
    path("", api.urls),
]

rlc_new/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("content.urls")),
    path("corpus/", include("corpus.urls")),
    path("api/", include("api.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

content/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


class Article(models.Model):
    """A class for news articles."""

    owner = models.ForeignKey(
        User, db_index=True, blank=True, null=True, on_delete=models.CASCADE
    )
    date = models.DateField(
        help_text="Выберите",
        verbose_name=_("date"),
    )
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)
    text_rus = models.TextField(
        help_text=_("Please enter the news text in Russian."),
        verbose_name=_("text in Russian"),
    )
    text_eng = models.TextField(
        help_text=_("Please enter the news text in English."),
        verbose_name=_("text in English"),
    )

    def __str__(self):
        return self.text_rus

    class Meta:
        verbose_name = _("article")
        verbose_name_plural = _("articles")


class Section(models.Model):
    """A class for storing the sections of the main page."""

    text_rus = models.TextField(
        help_text=_("Please enter the news text in Russian."),
        verbose_name=_("text in Russian"),
    )
    text_eng = models.TextField(
        help_text=_("Please enter the news text in English."),
        verbose_name=_("text in English"),
    )
    header_rus = models.CharField(
        max_length=100,
        help_text=_("Enter the name of the section in Russian"),
        verbose_name=_("name in Russian"),
    )
    header_eng = models.CharField(
        max_length=100,
        help_text=_("Enter the name of the section in English"),
        verbose_name=_("name in English"),
    )
    number = models.IntegerField(
        help_text=_("Please enter the number of the entry on the page"),
        verbose_name=_("entry number"),
    )

    class Meta:
        verbose_name = _("section")
        verbose_name_plural = _("sections")

    def __unicode__(self):
        return self.header_rus

corpus/models.py
from django.apps import apps
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import (
    SearchVectorField,
)
from django.db import models
from django.db import transaction
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from .utils.document_utils import send_post_save_signal, process_body_changes


class Author(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Author name"))

    class GenderChoices(models.TextChoices):
        M = "M", _("Male")
        F = "F", _("Female")
        # noinspection PyPep8
        O = "O", _("Other")

    gender = models.CharField(
        max_length=10, choices=GenderChoices.choices, verbose_name=_("Gender")
    )
    program = models.CharField(max_length=255, verbose_name=_("Program"))

    class LanguageBackgroundChoices(models.TextChoices):
        H = "H", _("Heritage")
        F = "F", _("Foreign")
        # noinspection PyPep8
        O = "O", _("Other")

    language_background = models.CharField(
        max_length=10,
        choices=LanguageBackgroundChoices.choices,
        verbose_name=_("Language background"),
    )

    class DominantLanguageChoices(models.TextChoices):
        ABK = "abk", _("Abkhazian")
        AZE = "aze", _("Azerbaijani")
        ALB = "alb", _("Albanian")
        AMH = "amh", _("Amharic")
        ENG = "eng", _("English")
        ARA = "ara", _("Arabic")
        ARM = "arm", _("Armenian")
        BEN = "ben", _("Bengali")
        BUL = "bul", _("Bulgarian")
        HUN = "hun", _("Hungarian")
        VIE = "vie", _("Vietnamese")
        DUT = "dut", _("Dutch")
        GRE = "gre", _("Greek")
        GEO = "geo", _("Georgian")
        DAG = "dag", _("Daghestanian")
        DAR = "dar", _("Dari")
        HEB = "heb", _("Hebrew")
        IND = "ind", _("Indonesian")
        SPA = "spa", _("Spanish")
        ITA = "ita", _("Italian")
        KAZ = "kaz", _("Kazakh")
        CHI = "chi", _("Chinese")
        KOR = "kor", _("Korean")
        KUR = "kur", _("Kurdish")
        KHM = "khm", _("Khmer")
        LAO = "lao", _("Lao")
        MAC = "mac", _("Macedonian")
        MON = "mon", _("Mongolian")
        GER = "ger", _("German")
        NEP = "nep", _("Nepali")
        NOR = "nor", _("Norwegian")
        POR = "por", _("Portuguese")
        PAS = "pas", _("Pashto")
        ROM = "rom", _("Romanian")
        SER = "ser", _("Serbian")
        SVK = "svk", _("Slovak")
        SLO = "slo", _("Slovenian")
        TAJ = "taj", _("Tajik")
        THA = "tha", _("Thai")
        TUR = "tur", _("Turkish")
        TURKMEN = "turkmen", _("Turkmen")
        UZB = "uzb", _("Uzbek")
        URD = "urd", _("Urdu")
        FAR = "far", _("Farsi")
        FIN = "fin", _("Finnish")
        FR = "fr", _("French")
        HIN = "hin", _("Hindi")
        CRO = "cro", _("Croatian")
        SHO = "sho", _("Czech")
        SWE = "swe", _("Swedish")
        SHONA = "shona", _("Shona")
        EST = "est", _("Estonian")
        JAP = "jap", _("Japanese")

    dominant_language = models.CharField(
        max_length=10,
        null=True,
        blank=False,
        choices=DominantLanguageChoices.choices,
        default=DominantLanguageChoices.ENG,
        db_index=True,
        verbose_name=_("Dominant language"),
    )

    favorite = models.BooleanField(default=False, verbose_name=_("Favourites"))

    source = models.CharField(
        max_length=200, null=True, blank=True, verbose_name=_("Source")
    )

    def __str__(self):
        return self.name

    def serialize(self):
        return {
            "name": self.name,
            "gender": self.gender,
            "program": self.program,
            "language_background": self.language_background,
            "dominant_language": self.dominant_language,
            "source": self.source,
        }


class Document(models.Model):
    """
    A document is a text that can be annotated.
    """

    # The title of the document
    title = models.CharField(max_length=200, verbose_name=_("Title"))
    # The owner of the document (FK to User)
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name=_("User"),
    )
    # The date when the document was created
    created_on = models.DateTimeField(auto_now_add=True, verbose_name=_("Created on"))

    # Дата написания текста
    date = models.IntegerField(null=True, blank=True, verbose_name=_("Written in"))

    # жанр текста
    class GenreChoices(models.TextChoices):
        ANSWERS = "answers", _("Answers to questions")
        NONACADEMIC = "nonacademic", _("Non–academic essay")
        ACADEMIC = "academic", _("Academic essay")
        BLOG = "blog", _("Blog")
        LETTER = "letter", _("Letter")
        STORY = "story", _("Story")
        PARAPHRASE = "paraphrase", _("Paraphrase")
        DEFINITION = "definition", _("Definition")
        BIO = "bio", _("Biography")
        DESCRIPTION = "description", _("Description")
        SUMMARY = "summary", _("Summary")
        OTHER = "other", _("Other")

    genre = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        db_index=True,
        verbose_name=_("Genre"),
        choices=GenreChoices.choices,
        default=GenreChoices.OTHER,
    )

    class LanguageLevelChoices(models.TextChoices):
        NOV = "NOV", "Novice"
        NL = "NL", "Novice Low"
        NM = "NM", "Novice Middle"
        NH = "NH", "Novice High"
        A1 = "A1", "A1"
        A2 = "A2", "A2"
        INT = "INT", "Intermediate"
        IL = "IL", "Intermediate Low"
        IM = "IM", "Intermediate Middle"
        IH = "IH", "Intermediate High"
        B1 = "B1", "B1"
        B2 = "B2", "B2"
        ADV = "ADV", "Advanced"
        AL = "AL", "Advanced Low"
        AM = "AM", "Advanced Middle"
        AH = "AH", "Advanced High"
        C1 = "C1", "C1"
        C2 = "C2", "C2"
        UNK = "UNK", "Unknown"

    language_level = models.CharField(
        max_length=10,
        null=True,
        blank=False,
        choices=LanguageLevelChoices.choices,
        db_index=True,
        verbose_name=_("Language level"),
    )

    # название подкорпуса
    class SubcorpusChoices(models.TextChoices):
        HSE = "HSE", "HSE"
        UNICE = "UNICE", "UNICE"
        RULEC = "RULEC", "RULEC"
        FIN = "FIN", "FIN"
        BERLIN = "BERLIN", "BERLIN"
        TOKYO = "TOKYO", "TOKYO"
        SFEDU = "SFEDU", "SFEDU"

    subcorpus = models.CharField(
        max_length=10,
        null=True,
        blank=True,
        choices=SubcorpusChoices.choices,
        db_index=True,
        default=SubcorpusChoices.HSE,
        verbose_name=_("Subcorpus"),
    )

    # The text of the document
    body = models.TextField(verbose_name=_("Text"))

    class StatusChoices(models.IntegerChoices):
        NEW = 0, _("New")
        ANNOTATED = 1, _("Annotated")
        CHECKED = 2, _("Checked")

    # The status of the document (new, annotated, checked)
    status = models.IntegerField(
        choices=StatusChoices.choices, default=0, verbose_name=_("Status")
    )

    author = models.ForeignKey(
        Author,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name=_("Author"),
    )

    time_limit = models.BooleanField(default=False, verbose_name=_("Time limit"))

    oral = models.BooleanField(default=False, verbose_name=_("Oral"))

    annotators = models.ManyToManyField(
        User,
        related_name="annotated_documents",
        blank=True,
        verbose_name=_("Annotators"),
    )

    def serialize(self):
        return {
            "id": self.id,
            "title": self.title,
            "user": self.user.username if self.user else None,
            "created_on": self.created_on.isoformat(),
            "date": self.date,
            "genre": self.genre,
            "subcorpus": self.subcorpus,
            "body": self.body,
            "status": self.get_status_display(),
            "author": self.author.serialize() if self.author else None,
            "time_limit": self.time_limit,
            "oral": self.oral,
            "language_level": self.language_level,
            "annotators": list(self.annotators.values_list("username", flat=True)),
            "sentences": self.serialize_sentences(),
        }

    def serialize_sentences(self):
        sentences = self.sentence_set.all()
        return [sentence.serialize() for sentence in sentences]

    # noinspection PyMethodParameters
    @receiver(post_save)
    def update_document_annotators(sender, instance, created, **kwargs):
        # noinspection PyPep8Naming,PyShadowingNames
        Annotation = apps.get_model("corpus", "Annotation")
        if created and sender == Annotation:
            instance.document.annotators.add(instance.user)

    @transaction.atomic
    def save(self, *args, **kwargs):
        body_changed = (
            not self.pk
            or Document.objects.only("body").get(pk=self.pk).body != self.body
        )
        super().save(*args, **kwargs)
        send_post_save_signal(self)
        if body_changed:
            process_body_changes(self)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title


def get_selectors(annotation_json):
    selectors = annotation_json["target"]["selector"]
    text_position_selector = [
        selector for selector in selectors if selector["type"] == "TextPositionSelector"
    ][0]
    text_quote_selector = [
        selector for selector in selectors if selector["type"] == "TextQuoteSelector"
    ][0]
    return (
        text_position_selector.get("start"),
        text_position_selector.get("end"),
        text_quote_selector.get("exact"),
    )

templates/add_document.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <form method="post" id="add-document-form">
          {% csrf_token %}
          <h3 class="mb-3">{% trans "Add document" %}</h3>
          <div class="alert alert-danger" role="alert"
               style="display: {% if form.non_field_errors %}block{% else %}none{% endif %};">
            {% for error in form.non_field_errors %}
              {{ error }}
            {% endfor %}
          </div>
          <div class="row mb-3">
            <div class="col-md-6">
              <div class="form-group">
                {{ form.title.label_tag }}
                {{ form.title }}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                {{ form.date.label_tag }}
                {{ form.date }}
              </div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-6">
              <div class="form-group">
                {{ form.genre.label_tag }}
                {{ form.genre }}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                {{ form.subcorpus.label_tag }}
                {{ form.subcorpus }}
              </div>
            </div>
          </div>
          <div class="form-group mb-2">
            {{ form.body.label_tag }}
            {{ form.body }}
          </div>
          <div class="row mb-3">
            <div class="col-md-6">
              <div class="form-group">
                {{ form.time_limit.label_tag }}
                {{ form.time_limit }}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                {{ form.oral.label_tag }}
                {{ form.oral }}
              </div>
            </div>
          </div>
          <ul class="nav nav-tabs mb-2">
            <li class="nav-item">
              <a class="nav-link active" id="add-author-tab" href="#" data-bs-toggle="tab"
                 data-bs-target="#author-fields">{% trans "New author" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="select-author-tab" href="#" data-bs-toggle="tab"
                 data-bs-target="#favorite-authors">{% trans "Saved author" %}</a>
            </li>
          </ul>
          <input type="hidden" id="author-selection-method" name="author_selection_method" value="manual">

          <div class="tab-content mb-4">
            {% include 'author_card.html' %}
            <div class="form-group tab-pane fade" id="favorite-authors">
              <label for="search-author">{{ favorite_author_form.selected_author.label }}</label>
              <input type="text" class="form-control" id="search-author"
                     placeholder="{% trans "Search for saved authors..." %}">
              {{ favorite_author_form.selected_author.as_hidden }}
            </div>
          </div>

          <div class="form-group mb-4">
            {{ form.language_level.label_tag }}
            {{ form.language_level }}
          </div>
          <button type="submit" class="btn btn-lg btn-primary">{% trans "Add" %}</button>
        </form>
      </div>
    </div>
  </div>
  <script>
    function disableFields(selector) {
      $(selector).find(':input').each(function () {
        $(this).prop('disabled', true);
      });
    }

    function enableFields(selector) {
      $(selector).find(':input').each(function () {
        $(this).prop('disabled', false);
      });
    }

    $(document).ready(function () {
      $("#add-author-tab").click(function () {
        $("#author-fields").addClass("active show");
        $("#favorite-authors").removeClass("active show");
        $("#add-author-tab").addClass("active");
        $("#select-author-tab").removeClass("active");
        $("#author-selection-method").val("manual");
        enableFields('#author-fields');
        disableFields('#favorite-authors');
      });

      $("#select-author-tab").click(function () {
        $("#author-fields").removeClass("active show");
        $("#favorite-authors").addClass("active show");
        $("#add-author-tab").removeClass("active");
        $("#select-author-tab").addClass("active");
        $("#author-selection-method").val("dropdown");
        enableFields('#favorite-authors');
        disableFields('#author-fields');
      });

      // Initially disable fields in the non-focused form
      disableFields('#favorite-authors');

      $("#add-document-form").submit(function (event) {
        // Check if the form is valid
        if (!this.checkValidity()) {
          event.preventDefault();
          event.stopPropagation();
        }
      });

      {% if preselect_favorite_author %}
        $("#select-author-tab").click();
      {% endif %}
    });
    $(document).ready(function () {
      var authors = [
        {% for author in favorite_author_form.selected_author.field.queryset %}
          {
            value: "{{ author.pk }}",
            label: "{{ author }}"
          }{% if not forloop.last %},{% endif %}
        {% endfor %}
      ];

      $("#search-author").autocomplete({
        minLength: 0,
        source: authors,
        select: function (event, ui) {
          $("#{{ favorite_author_form.selected_author.auto_id }}").val(ui.item.value);
          $(this).val(ui.item.label);
          event.preventDefault();
        }
      }).focus(function () {
        $(this).autocomplete("search", "");
      });
    });
  </script>
{% endblock %}

templates/annotate.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ document.title }}{% endblock %}
{% load i18n %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            {% if perms.corpus.change_document %}
              <div class="d-flex justify-content-between align-items-center mb-3">
                <div class="form-group mb-0">
                  <label for="document-status" class="me-2">{% trans "Document status" %}</label>
                  <select class="form-select form-select-sm d-inline-block" id="document-status" style="width: auto;">
                    <option value="0" {% if document.status == 0 %}selected{% endif %}>{% trans "Not annotated" %}</option>
                    <option value="1" {% if document.status == 1 %}selected{% endif %}>{% trans "Annotated" %}</option>
                    <option value="2" {% if document.status == 2 %}selected{% endif %}>{% trans "Checked" %}</option>
                  </select>
                </div>
                <button id="hideIdsButton" class="btn btn-primary mb-3" data-trans="{% trans 'Hide IDs' %}">
                  <i id="buttonIcon" class="fa fa-eye-slash"></i>
                  <span id="buttonText">{% trans 'Hide IDs' %}</span>
                </button>
              </div>
            {% else %}
              <button id="hideIdsButton" class="btn mb-3" data-trans="{% trans 'Hide IDs' %}">
                <i id="buttonIcon" class="fa fa-eye-slash"></i>
                <span id="buttonText">{% trans 'Hide IDs' %}</span>
              </button>
            {% endif %}

            <style>
                #hideIdsButton {
                background-color: transparent;
                border: none inherit;
                color: inherit;
                padding: 0;
              }

              #hideIdsButton:hover {
                background-color: transparent;
                color: inherit;
                border-color: inherit;
              }
            </style>
          <script>
          $(document).ready(function () {

            function toggleIdsVisibility() {
              $('.id-style').toggle();
            }


            $('#hideIdsButton').click(function (event) {
              event.preventDefault();

              toggleIdsVisibility();

              const currentText = $('#buttonText').text();
              const buttonIcon = $('#buttonIcon');
              if (currentText === '{% trans "Hide IDs" %}') {
                $('#buttonText').text('{% trans "Show IDs" %}');
                buttonIcon.removeClass('fa-eye-slash').addClass('fa-eye');
                $(this).removeClass('btn-primary').addClass('btn-secondary');
                localStorage.setItem('hideIdsStatus', 'hidden');
              } else {
                $('#buttonText').text('{% trans "Hide IDs" %}');
                buttonIcon.removeClass('fa-eye').addClass('fa-eye-slash');
                $(this).removeClass('btn-secondary').addClass('btn-primary');
                localStorage.setItem('hideIdsStatus', 'shown');
              }
            });
            function applySavedVisibilityState() {
              const status = localStorage.getItem('hideIdsStatus');
              if (status === 'hidden') {
                toggleIdsVisibility();
                $('#buttonText').text('{% trans "Show IDs" %}');
                $('#buttonIcon').removeClass('fa-eye-slash').addClass('fa-eye');
                $('#hideIdsButton').removeClass('btn-primary').addClass('btn-secondary');
              }
            }
            applySavedVisibilityState();
          });
        </script>

            {% include 'document_card.html' with annotate_view=True %}
            {% for sentence in sentences %}
              {% include 'sentence_card.html' with sentence=sentence %}
            {% endfor %}
            <p class="card-text"><small class="text-muted">{{ document.created_on }}</small></p>
          </div>
        </div>
      </div>
      <div class="col-md-4 card card-body">
        <ul class="nav custom-nav" id="navContainer">
        </ul>
      </div>
      <script src="{% static 'js/err_features.js' %}"></script>
      <script>
        const navContainer = document.getElementById('navContainer');

        // Loop through each section in errFeatures
        for (const section in errFeatures) {
          const sectionItem = document.createElement('li');
          sectionItem.textContent = section;

          const subsectionList = document.createElement('ul');

          // Loop through each subsection in the current section
          for (const subsection in errFeatures[section]) {
            const subsectionItem = document.createElement('li');
            const link = document.createElement('a');
            link.href = '#';
            link.dataset.toggle = 'tooltip';
            link.title = errFeatures[section][subsection];
            link.innerHTML = `<i class="fas fa-question"></i>`;

            subsectionItem.textContent = `${subsection} `;
            subsectionItem.appendChild(link);
            subsectionList.appendChild(subsectionItem);
          }

          sectionItem.appendChild(subsectionList);
          navContainer.appendChild(sectionItem);
        }
      </script>
    </div>
  </div>
  <script>
    $("#document-status").change(function () {
      let status = $(this).val();
      let documentId = "{{ document.id }}";
      let csrfToken = getCSRFToken();

      $.ajax({
        url: "{% url 'update_document_status' document.id %}",
        method: "POST",
        data: {
          'status': status,
          'csrfmiddlewaretoken': csrfToken,
        },
        success: function (data) {
          if (data.status === 'success') {
            console.log("Document status updated successfully.");
            // reload the page
            location.reload();
          } else {
            console.error("Error updating document status.");
          }
        },
        error: function () {
          console.error("Error updating document status.");
        }
      });
    });

    $(document).ready(function () {
      $('[data-toggle="tooltip"]').tooltip();
    });

    function updateCorrections(sentenceId) {
      const url = `/api/get_corrections/${sentenceId}`;

      $.ajax({
        type: "GET",
        url: url,
        success: function (response) {
          // Update the correction and alt_correction fields on the page
          const correction = response.correction;
          const altCorrection = response.alt_correction;

          $(`#correction-${sentenceId}`).text(correction);
          $(`#alt-correction-${sentenceId}`).text(altCorrection);
        },
        error: function (xhr, status, error) {
          console.error("Error updating corrections:", error);
        }
      });
    }

    function refreshCorrections() {
      {% for sentence in sentences %}
        updateCorrections({{ sentence.id }});
      {% endfor %}
    }


    document.addEventListener('DOMContentLoaded', function () {
      initRecogito(
          {% if perms.corpus.add_annotation %}true{% else %}false{% endif %},
          {% if user.is_authenticated %}true{% else %}false{% endif %}
      );
    });


    function getSentenceErrors(sentence_id) {
      const url = `/api/get_sentence_errors/${sentence_id}`;

      $.ajax({
        type: "GET",
        url: url,
        dataType: 'json',
        success: function (data) {
          const errors = data.errors;

          // Correctly define sentenceElement here before using it
          const sentenceElement = document.getElementById('sentence-' + sentence_id);
          const wordSpans = sentenceElement.getElementsByTagName('span');
          for (let i = 0; i < wordSpans.length; i++) {
            // If the span's text is in the errors array, add the "error" class
            if (errors.includes(wordSpans[i].innerText)) {
              wordSpans[i].classList.add('error');
            }
          }
        }
      });
    }


    $(document).ready(function () {
      {% for sentence in sentences %}
        getSentenceErrors({{ sentence.id }});
      {% endfor %}
    });
  </script>
{% endblock %}

templates/create_article.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans "Create article" %}
{% endblock %}

{% block content %}
  <script src="{% static "js/libs/ckeditor5-build-classic/ckeditor.js" %}"></script>
  {% if LANGUAGE_CODE == 'ru' %}
    <script src="{% static "js/libs/ckeditor5-build-classic/translations/ru.js" %}"></script>
  {% endif %}
  <h1>{% trans "Create article" %}</h1>
  <!-- Check if form contains any errors -->
  {% if form.errors %}
    <div class="alert alert-danger">
      <ul>
        <!-- Iterate over the form.errors dict -->
        {% for field, errors in form.errors.items %}
          <!-- Iterate over the list of errors in the current field -->
          {% for error in errors %}
            <li><strong>{{ field }}:</strong> {{ error }}</li>
          {% endfor %}
        {% endfor %}
      </ul>
    </div>
  {% endif %}
  <form method="POST">
    {% csrf_token %}
    {{ form.owner }}
    <p>
      <label for="{{ form.date.id_for_label }}">{{ form.date.label }}</label><br>
      {{ form.date }}
    </p>
    <p>
      <label for="editor-rus">{% trans "Text in Russian:" %}</label><br>
      <textarea name="text_rus" id="editor-rus"></textarea>
    </p>
    <p>
      <label for="editor-eng">{% trans "Text in English:" %}</label><br>
      <textarea name="text_eng" id="editor-eng"></textarea>
    </p>
    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
  </form>

  <script>
    ClassicEditor
        .create(document.querySelector('#editor-rus'), {
          language: '{{ LANGUAGE_CODE }}'
        })
        .catch(error => {
          console.error(error);
        });
    ClassicEditor
        .create(document.querySelector('#editor-eng'), {
          language: '{{ LANGUAGE_CODE }}'
        })
        .catch(error => {
          console.error(error);
        });
  </script>
{% endblock content %}

templates/edit_author.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
  <h3>{% trans "Edit author" %}</h3>
  <form method="post">
    {% csrf_token %}
    {% include 'author_card.html' %}
    <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
  </form>
{% endblock %}

templates/news.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
	{% trans "News" %}
{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <a href="{% url 'create_article' %}" class="btn btn-secondary btn-lg active mt-2 mb-4" role="button"
       aria-pressed="true">
      <i class="bi bi-pencil-square"></i>
      {% trans "Add news" %}
    </a>
  {% endif %}

  {% for article in articles %}
    <div id="section{{ forloop.counter }}" class="mb-5">
      <h2>{{ article.date }}</h2>
      <div class="card border-1">
        <div class="card-body position-relative" style="padding-right: 50px;">
          {% if LANGUAGE_CODE == 'ru' %}
            {{ article.text_rus|safe }}
          {% else %}
            {{ article.text_eng|safe }}
          {% endif %}
          {% if perms.content.delete_article %}
            <a href="#" class="btn btn-danger position-absolute bottom-0 end-0 m-2" data-bs-toggle="modal"
               data-bs-target="#deleteModal{{ forloop.counter }}" role="button" aria-pressed="true">
              <i class="bi bi-trash"></i>
            </a>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- Delete Confirmation Modal -->
    <div class="modal fade" id="deleteModal{{ forloop.counter }}" tabindex="-1"
         aria-labelledby="deleteModalLabel{{ forloop.counter }}" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel{{ forloop.counter }}">{% trans "Confirm Delete" %}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            {% trans "Are you sure you want to delete this article?" %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Cancel" %}</button>
            <a href="{% url 'delete_article' pk=article.pk %}" class="btn btn-danger">{% trans "Delete" %}</a>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

{% endblock content %}

templates/user_profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ user.username }}'s Profile</h1>
  <p>Email: {{ user.email }}</p>
  <p>First name: {{ user.first_name }}</p>
  <p>Last name: {{ user.last_name }}</p>
{% endblock %}