api/urls.py
from django.urls import path
from .views import api

urlpatterns = [
    path("", api.urls),
]

rlc_new/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("content.urls")),
    path("corpus/", include("corpus.urls")),
    path("api/", include("api.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

corpus/models.py
from django.apps import apps
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import (
    SearchVectorField,
)
from django.db import models
from django.db import transaction
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from .utils.document_utils import send_post_save_signal, process_body_changes


class Author(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Author name"))

    class GenderChoices(models.TextChoices):
        M = "M", _("Male")
        F = "F", _("Female")
        # noinspection PyPep8
        O = "O", _("Other")

    gender = models.CharField(
        max_length=10, choices=GenderChoices.choices, verbose_name=_("Gender")
    )
    program = models.CharField(max_length=255, verbose_name=_("Program"))

    class LanguageBackgroundChoices(models.TextChoices):
        H = "H", _("Heritage")
        F = "F", _("Foreign")
        # noinspection PyPep8
        O = "O", _("Other")

    language_background = models.CharField(
        max_length=10,
        choices=LanguageBackgroundChoices.choices,
        verbose_name=_("Language background"),
    )

    class DominantLanguageChoices(models.TextChoices):
        ABK = "abk", _("Abkhazian")
        AZE = "aze", _("Azerbaijani")
        ALB = "alb", _("Albanian")
        AMH = "amh", _("Amharic")
        ENG = "eng", _("English")
        ARA = "ara", _("Arabic")
        ARM = "arm", _("Armenian")
        BEN = "ben", _("Bengali")
        BUL = "bul", _("Bulgarian")
        HUN = "hun", _("Hungarian")
        VIE = "vie", _("Vietnamese")
        DUT = "dut", _("Dutch")
        GRE = "gre", _("Greek")
        GEO = "geo", _("Georgian")
        DAG = "dag", _("Daghestanian")
        DAR = "dar", _("Dari")
        HEB = "heb", _("Hebrew")
        IND = "ind", _("Indonesian")
        SPA = "spa", _("Spanish")
        ITA = "ita", _("Italian")
        KAZ = "kaz", _("Kazakh")
        CHI = "chi", _("Chinese")
        KOR = "kor", _("Korean")
        KUR = "kur", _("Kurdish")
        KHM = "khm", _("Khmer")
        LAO = "lao", _("Lao")
        MAC = "mac", _("Macedonian")
        MON = "mon", _("Mongolian")
        GER = "ger", _("German")
        NEP = "nep", _("Nepali")
        NOR = "nor", _("Norwegian")
        POR = "por", _("Portuguese")
        PAS = "pas", _("Pashto")
        ROM = "rom", _("Romanian")
        SER = "ser", _("Serbian")
        SVK = "svk", _("Slovak")
        SLO = "slo", _("Slovenian")
        TAJ = "taj", _("Tajik")
        THA = "tha", _("Thai")
        TUR = "tur", _("Turkish")
        TURKMEN = "turkmen", _("Turkmen")
        UZB = "uzb", _("Uzbek")
        URD = "urd", _("Urdu")
        FAR = "far", _("Farsi")
        FIN = "fin", _("Finnish")
        FR = "fr", _("French")
        HIN = "hin", _("Hindi")
        CRO = "cro", _("Croatian")
        SHO = "sho", _("Czech")
        SWE = "swe", _("Swedish")
        SHONA = "shona", _("Shona")
        EST = "est", _("Estonian")
        JAP = "jap", _("Japanese")

    dominant_language = models.CharField(
        max_length=10,
        null=True,
        blank=False,
        choices=DominantLanguageChoices.choices,
        default=DominantLanguageChoices.ENG,
        db_index=True,
        verbose_name=_("Dominant language"),
    )

    favorite = models.BooleanField(default=False, verbose_name=_("Favourites"))

    source = models.CharField(
        max_length=200, null=True, blank=True, verbose_name=_("Source")
    )

    def __str__(self):
        return self.name

    def serialize(self):
        return {
            "name": self.name,
            "gender": self.gender,
            "program": self.program,
            "language_background": self.language_background,
            "dominant_language": self.dominant_language,
            "source": self.source,
        }


class Document(models.Model):
    """
    A document is a text that can be annotated.
    """

    # The title of the document
    title = models.CharField(max_length=200, verbose_name=_("Title"))
    # The owner of the document (FK to User)
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name=_("User"),
    )
    # The date when the document was created
    created_on = models.DateTimeField(auto_now_add=True, verbose_name=_("Created on"))

    # Дата написания текста
    date = models.IntegerField(null=True, blank=True, verbose_name=_("Written in"))

    # жанр текста
    class GenreChoices(models.TextChoices):
        ANSWERS = "answers", _("Answers to questions")
        NONACADEMIC = "nonacademic", _("Non–academic essay")
        ACADEMIC = "academic", _("Academic essay")
        BLOG = "blog", _("Blog")
        LETTER = "letter", _("Letter")
        STORY = "story", _("Story")
        PARAPHRASE = "paraphrase", _("Paraphrase")
        DEFINITION = "definition", _("Definition")
        BIO = "bio", _("Biography")
        DESCRIPTION = "description", _("Description")
        SUMMARY = "summary", _("Summary")
        OTHER = "other", _("Other")

    genre = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        db_index=True,
        verbose_name=_("Genre"),
        choices=GenreChoices.choices,
        default=GenreChoices.OTHER,
    )

    class LanguageLevelChoices(models.TextChoices):
        NOV = "NOV", "Novice"
        NL = "NL", "Novice Low"
        NM = "NM", "Novice Middle"
        NH = "NH", "Novice High"
        A1 = "A1", "A1"
        A2 = "A2", "A2"
        INT = "INT", "Intermediate"
        IL = "IL", "Intermediate Low"
        IM = "IM", "Intermediate Middle"
        IH = "IH", "Intermediate High"
        B1 = "B1", "B1"
        B2 = "B2", "B2"
        ADV = "ADV", "Advanced"
        AL = "AL", "Advanced Low"
        AM = "AM", "Advanced Middle"
        AH = "AH", "Advanced High"
        C1 = "C1", "C1"
        C2 = "C2", "C2"
        UNK = "UNK", "Unknown"

    language_level = models.CharField(
        max_length=10,
        null=True,
        blank=False,
        choices=LanguageLevelChoices.choices,
        db_index=True,
        verbose_name=_("Language level"),
    )

    # название подкорпуса
    class SubcorpusChoices(models.TextChoices):
        HSE = "HSE", "HSE"
        UNICE = "UNICE", "UNICE"
        RULEC = "RULEC", "RULEC"
        FIN = "FIN", "FIN"
        BERLIN = "BERLIN", "BERLIN"
        TOKYO = "TOKYO", "TOKYO"
        SFEDU = "SFEDU", "SFEDU"

    subcorpus = models.CharField(
        max_length=10,
        null=True,
        blank=True,
        choices=SubcorpusChoices.choices,
        db_index=True,
        default=SubcorpusChoices.HSE,
        verbose_name=_("Subcorpus"),
    )

    # The text of the document
    body = models.TextField(verbose_name=_("Text"))

    class StatusChoices(models.IntegerChoices):
        NEW = 0, _("New")
        ANNOTATED = 1, _("Annotated")
        CHECKED = 2, _("Checked")

    # The status of the document (new, annotated, checked)
    status = models.IntegerField(
        choices=StatusChoices.choices, default=0, verbose_name=_("Status")
    )

    author = models.ForeignKey(
        Author,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name=_("Author"),
    )

    time_limit = models.BooleanField(default=False, verbose_name=_("Time limit"))

    oral = models.BooleanField(default=False, verbose_name=_("Oral"))

    annotators = models.ManyToManyField(
        User,
        related_name="annotated_documents",
        blank=True,
        verbose_name=_("Annotators"),
    )

    def serialize(self):
        return {
            "id": self.id,
            "title": self.title,
            "user": self.user.username if self.user else None,
            "created_on": self.created_on.isoformat(),
            "date": self.date,
            "genre": self.genre,
            "subcorpus": self.subcorpus,
            "body": self.body,
            "status": self.get_status_display(),
            "author": self.author.serialize() if self.author else None,
            "time_limit": self.time_limit,
            "oral": self.oral,
            "language_level": self.language_level,
            "annotators": list(self.annotators.values_list("username", flat=True)),
            "sentences": self.serialize_sentences(),
        }

    def serialize_sentences(self):
        sentences = self.sentence_set.all()
        return [sentence.serialize() for sentence in sentences]

    # noinspection PyMethodParameters
    @receiver(post_save)
    def update_document_annotators(sender, instance, created, **kwargs):
        # noinspection PyPep8Naming,PyShadowingNames
        Annotation = apps.get_model("corpus", "Annotation")
        if created and sender == Annotation:
            instance.document.annotators.add(instance.user)

    @transaction.atomic
    def save(self, *args, **kwargs):
        body_changed = (
            not self.pk
            or Document.objects.only("body").get(pk=self.pk).body != self.body
        )
        super().save(*args, **kwargs)
        send_post_save_signal(self)
        if body_changed:
            process_body_changes(self)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title


def get_selectors(annotation_json):
    selectors = annotation_json["target"]["selector"]
    text_position_selector = [
        selector for selector in selectors if selector["type"] == "TextPositionSelector"
    ][0]
    text_quote_selector = [
        selector for selector in selectors if selector["type"] == "TextQuoteSelector"
    ][0]
    return (
        text_position_selector.get("start"),
        text_position_selector.get("end"),
        text_quote_selector.get("exact"),
    )

templates/partials/document/author_card.html
<div id="author-fields" class="tab-pane fade show active">
  <div class="row mb-3">
    <div class="col-md-6">
      <div class="form-group">
        {{ author_form.name.label_tag }}
        {{ author_form.name }}
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        {{ author_form.gender.label_tag }}
        {{ author_form.gender }}
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <div class="form-group">
        {{ author_form.program.label_tag }}
        {{ author_form.program }}
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        {{ author_form.language_background.label_tag }}
        {{ author_form.language_background }}
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <div class="form-group">
        {{ author_form.dominant_language.label_tag }}
        {{ author_form.dominant_language }}
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        {{ author_form.source.label_tag }}
        {{ author_form.source }}
      </div>
    </div>
  </div>
  <div class="form-group mb-3">
    {{ author_form.favorite.label_tag }}
    {{ author_form.favorite }}
  </div>
</div>

templates/partials/document/document_card.html
{% load templatetags %}
{% load i18n %}
<div class="card mb-3">
  <div class="card-body">
    <!-- Accordion -->
    <div class="accordion accordion-flush mb-2 dark-accordion shadow-none" id="detailsAccordion{{ document.id }}">
      <div class="accordion-item">
        <h2 class="accordion-header" id="detailsAccordionHeading{{ document.id }}">
          <button class="accordion-button collapsed rounded-0 shadow-sm fw-bold" type="button"
                  data-bs-toggle="collapse" data-bs-target="#detailsAccordionCollapse{{ document.id }}"
                  aria-expanded="false"
                  aria-controls="detailsAccordionCollapse">
            {% if title_query %}
              <h5 class="card-title m-0">{{ document.title|highlight_search:title_query }}</h5>
            {% else %}
              <h5 class="card-title m-0">{{ document.title }}</h5>
            {% endif %}
          </button>
        </h2>
        <div id="detailsAccordionCollapse{{ document.id }}" class="accordion-collapse collapse"
             aria-labelledby="detailsAccordionHeading{{ document.id }}">
          <div class="accordion-body">
            <div class="row">
              <div class="col-md-5 mb-3">
                <dl class="row">
                  <dt class="col-sm-5">{% trans "Added" %}:</dt>
                  <dd class="col-sm-7">{{ document.created_on }}</dd>

                  <dt class="col-sm-5">{% trans "Written in" %}:</dt>
                  <dd class="col-sm-7">{{ document.date }}</dd>

                  <dt class="col-sm-5">{% trans "Genre" %}:</dt>
                  <dd class="col-sm-7">{{ document.get_genre_display }}</dd>

                  <dt class="col-sm-5">{% trans "Subcorpus" %}:</dt>
                  <dd class="col-sm-7">{{ document.get_subcorpus_display }}</dd>

                  <dt class="col-sm-5">{% trans "Language level" %}:</dt>
                  <dd class="col-sm-7">{{ document.get_language_level_display }}</dd>

                  <dt class="col-sm-5">{% trans "Status" %}:</dt>
                  <dd class="col-sm-7">{{ document.get_status_display }}</dd>

                  <dt class="col-sm-5">{% trans "Owner" %}:</dt>
                  <dd class="col-sm-7">{{ document.user.username }}</dd>
                </dl>
              </div>
              <div class="col-md-7 mb-3">
                <dl class="row">
                  <dt class="col-sm-4">{% trans "Author" %}:</dt>
                  <dd class="col-sm-8">{{ document.author.name }}</dd>

                  <dt class="col-sm-4">{% trans "Gender" %}:</dt>
                  <dd class="col-sm-8">{{ document.author.get_gender_display }}</dd>

                  <dt class="col-sm-4">{% trans "Dominant language" %}:</dt>
                  <dd class="col-sm-8">{{ document.author.get_dominant_language_display }}</dd>

                  <dt class="col-sm-4">{% trans "Source" %}:</dt>
                  <dd class="col-sm-8">{{ document.author.source }}</dd>

                  <dt class="col-sm-4">{% trans "Language background" %}:</dt>
                  <dd class="col-sm-8">{{ document.author.get_language_background_display }}</dd>

                  <dt class="col-sm-4">{% trans "Program" %}:</dt>
                  <dd class="col-sm-8">{{ document.author.program }}</dd>
                </dl>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Accordion -->
    {% if not annotate_view %}
      {% if body_query %}
        <p class="card-text">{{ document.body|highlight_search:body_query }}</p>
      {% else %}
        <p class="card-text">{{ document.body }}</p>
      {% endif %}
    {% endif %}
    <div class="d-flex justify-content-between align-items-center">
      {% if not annotate_view %}
        {% if perms.corpus.add_annotation %}
          <div class="d-flex align-items-center">
            <a href="{% url 'annotate' document.id %}" class="btn btn-primary"><i
                class="bi bi-highlighter"></i> {% trans "Annotate" %}</a>
          </div>
        {% else %}
          <div class="d-flex align-items-center">
            <a href="{% url 'annotate' document.id %}" class="btn btn-primary"><i
                class="bi bi-eye"></i> {% trans "View" %}</a>
          </div>
        {% endif %}
      {% endif %}
      <div class="d-flex">
        {% if perms.corpus.change_document %}
          <a href="{% url 'edit_document' document_id=document.id %}"
             class="btn btn-secondary border-0 shadow-none me-2">
            <i class="bi bi-pencil-square"></i> {% trans "Edit" %}
          </a>
        {% endif %}
        {% if perms.corpus.delete_document %}
          <button type="button" class="btn btn-danger border-0 shadow-none" data-bs-toggle="modal"
                  data-bs-target="#deleteConfirmationModal" data-document-id="{{ document.id }}">
            <i class="bi bi-trash"></i> {% trans "Delete" %}
          </button>
          <div class="modal fade" id="deleteConfirmationModal" tabindex="-1"
               aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteConfirmationModalLabel">{% trans "Confirm deletion" %}</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  {% trans "Are you sure you want to delete this document?" %}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Cancel" %}</button>
                  <a href="#" id="confirmDelete" class="btn btn-danger">{% trans "Delete" %}</a>
                </div>
              </div>
            </div>
          </div>
          <script>
            $(document).ready(function () {
              $(document).on('click', 'button[data-bs-toggle="modal"]', function () {
                const documentId = $(this).data('document-id');
                const deleteUrl = "{% url 'delete_document' document_id=123 %}".replace('123', documentId);
                $('#confirmDelete').attr('href', deleteUrl);
              });
            });
          </script>
        {% endif %}
        <h5 class="text-muted mt-3 ms-3 mb-0 id-style show" style="font-size: 12px; font-style: italic;">
          ID: {{ document.id }}
        </h5>

      </div>
    </div>
  </div>
</div>

templates/partials/document/sentence_card.html
{% load i18n %}

<div class="card mb-2" style="max-width: 100%;" data-card-id="{{ sentence.id }}">
  <div class="card-body position-relative pb-4" id="sentence-card-{{ sentence.id }}">
    <div class="d-flex align-items-center">
      <div id="sentence-{{ sentence.id }}" data-sentence-id="{{ sentence.id }}" data-document-id="{{ document.id }}"
           data-user-id="{{ user.id }}" data-alt="false" class="sentence">{{ sentence.markup|safe }}</div>
      {% if perms.corpus.add_annotation %}
        <button id="auto-annotate-btn-{{ sentence.id }}" class="btn btn-sm btn-outline-primary ms-2">
          <i class="bi bi-magic"></i>
        </button>{% endif %}
    </div>
    <div class="mt-2" style="display: none;" id="corrected-sentence-container-{{ sentence.id }}">
      <div class="input-group">
        <input id="corrected-sentence-input-{{ sentence.id }}" class="form-control" type="text"
               placeholder="{% trans 'Enter the corrected sentence' %}">
        <button id="submit-corrected-sentence-btn-{{ sentence.id }}" class="btn btn-sm btn-primary"
                onclick="submitCorrectedSentence({{ sentence.id }}, {{ sentence.document.id }})">
          {% trans "Submit" %}
        </button>
      </div>
    </div>
    <div id="correction-{{ sentence.id }}" data-alt="false"
         class="correction mb-2">
      {{ sentence.correction }}
    </div>

    <div class="accordion" id="sentenceAccordion-{{ sentence.id }}">
      <div class="accordion-item">
        <h2 class="accordion-header" id="altSentenceHeading-{{ sentence.id }}">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                  data-bs-target="#altSentenceCollapse-{{ sentence.id }}" aria-expanded="false"
                  aria-controls="altSentenceCollapse-{{ sentence.id }}">
            {% trans "Alternative correction" %}
          </button>
        </h2>
        <div id="altSentenceCollapse-{{ sentence.id }}" class="accordion-collapse collapse"
             aria-labelledby="altSentenceHeading-{{ sentence.id }}">
          <div class="accordion-body">
            <div id="alt-sentence-{{ sentence.id }}" data-sentence-id="{{ sentence.id }}"
                 data-document-id="{{ document.id }}" data-user-id="{{ user.id }}" data-alt="true"
                 class="sentence">{{ sentence.markup|safe }}</div>
            <div id="alt-correction-{{ sentence.id }}" data-alt="true"
                 class="correction">
              {{ sentence.alt_correction }}
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
<div id="recogito-{{ sentence.id }}" class="recogito"></div>